import Provider from "@/components/Provider";
import "./globals.css";
import { Outfit } from 'next/font/google'
import { ThemeProvider } from "@/ThemeProvider";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const outfit =  Outfit({subsets: ['latin']})

export default function RootLayout({ children }) {
  return (
      <html lang="en">
        <Provider>
          <ThemeProvider>
            <body className={`${outfit.className}`}>
                {children}
            </body>
          </ThemeProvider>
        </Provider>
      </html>
  );
}
